# Generated by Django 4.0.6 on 2022-10-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenspotify',
            name='refresh_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
