# Generated by Django 4.0.6 on 2022-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_part', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
