# Generated by Django 4.0.6 on 2022-09-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.IntegerField(default=False, max_length=5, unique=True)),
                ('room_host', models.CharField(max_length=50, unique=True)),
                ('can_guest_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
