# Generated by Django 4.0.6 on 2022-09-25 04:13

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_room_code_alter_room_votes_to_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default=api.models.code_generator, max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
